name: Trigger auto deployment for homework0507

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/homework0507-AutoDeployTrigger-8812dcb2-d7fe-4b9b-b2f3-34a5b9525a6c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HOMEWORK0507_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.HOMEWORK0507_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOMEWORK0507_REGISTRY_PASSWORD }}
          containerAppName: homework0507
          resourceGroup: 0507homework
          imageToBuild: ghcr.io/ghcr.io/ianchung930328/my-spring-app:${{ github.sha }}
          
            

     

