name: Trigger auto deployment for homework0507

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/homework0507-AutoDeployTrigger-a6cc45c4-2ec3-41a9-9b18-a80f72dfcb0a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HOMEWORK0507_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOMEWORK0507_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOMEWORK0507_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/workspaces/JPA-homework/demo
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ianchung930328/my-spring-app:latest
          registryUsername: ${{ secrets.HOMEWORK0507_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOMEWORK0507_REGISTRY_PASSWORD }}
          containerAppName: homework0507
          resourceGroup: 0507homework
          imageToBuild: ianchung930328/my-spring-app:latest/homework0507:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


